name: Continuous Delivery

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
        paths-ignore:
            - '**.md'

env:
    DOCKER_BASE_NAME: ghcr.io/xavier2p/mdbook
    TAG_NAME_LATEST: latest
    BASE_IMAGE: alpine:3.16

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    package:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
            packages: write
        env:
            DOCKER_CLI_EXPERIMENTAL: enabled
            DOCKER_BUILDKIT: 1
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Get mdbook version
              id: get-mdbook-version
              run: echo "::set-output name=version::$(make get-mdbook-version)"

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v2
              env:
                  PKG_TAG: '${{ env.DOCKER_BASE_NAME }}:v${{ steps.get-mdbook-version.outputs.version }}'
                  PKG_TAG_LATEST: '${{ env.DOCKER_BASE_NAME }}:${{ env.TAG_NAME_LATEST }}'
              with:
                  context: .
                  file: ./Dockerfile
                  tags: |
                      ${{ env.PKG_TAG }}
                      ${{ env.PKG_TAG_LATEST }}
                  platforms: linux/arm64
                  build-args: |
                      MDBOOK_VERSION=${{ steps.get-mdbook-version.outputs.version }}
                      BASE_IMAGE=${{ env.BASE_IMAGE }}
                  push: true

    release:
        runs-on: ubuntu-latest
        steps:
            - name: Create Release
              id: create_release
              uses: comnoco/create-release-action@v2.0.5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: mdBook ${{ github.ref }}
                  body: |
                      New version of mdBook in Docker for ARM available!
                      Check the [package page](https://github.com/Xavier2p/docker-mdbook-arm/pkgs/container/mdbook) to see it!
                  draft: false
                  prerelease: false
